# Generated by Django 5.2.13 on 2026-05-02 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_score', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attack_type', models.CharField(blank=True, max_length=100, null=True)),
                ('decision', models.CharField(blank=True, max_length=20, null=True)),
                ('user_input', models.TextField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usual_ip_prefixes', models.JSONField(default=dict)),
                ('usual_device', models.CharField(blank=True, max_length=100, null=True)),
                ('usual_login_start', models.IntegerField(default=0)),
                ('usual_login_end', models.IntegerField(default=23)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.chatbotuser')),
            ],
        ),
    ]
